### PR TITLE
Timing improvements

### PR DESCRIPTION
**Pull request by malinges**
Timing improvements
    
Changes:
- pull CLK low during DIO initialization to avoid sending a start signal
  by mistake
- simpler `tm1637_start()` (less pin level changes and delays)
- safer `tm1637_stop()` (added a delay)
- update DIO level after the falling edge of CLK (instead of right
  before the raising edge of CLK) to make the signal more resilient
- set DIO as input during the whole TM1637 ACK duration to avoid having
  both chips trying to drive DIO at the same time (short)
- increase frequency to around 100kHz, which reduces the full display
  update time from around 20ms to less than 2ms

### CODE REVIEW

**Comment by malinges** [comment]
Before:

scrn-2020-09-13-15-15-48

DIO changes just before the rising edge of CLK. This is probably what causes the recurring transmission errors (the pink "N": NACK).

After:

scrn-2020-09-13-15-18-55

DIO changes on the falling edge of CLK, which seems to get rid of the transmission errors, even at much higher clock rates.

**Comment by malinges** [comment]
Also, about 19.3ms to update 4 digits before the changes:

scrn-2020-09-13-15-46-50

Down to about 17.1ms after:

scrn-2020-09-13-15-47-51

**Comment by malinges** [comment]
Wait, I just noticed this doesn't seem to work with an ESP32 running at 240MHz (I was doing my tests at 160MHz). The signal looks good, but for some reason the TM1637 doesn't ACK anything at all, and the display stays blank.

But it doesn't seem to work with the code from the master branch either, so it doesn't seem like this is caused by my changes.

Did you ever get your library to work on an ESP32 running at 240MHz? I'm wondering if this might be caused by my specific unit.

**Comment by AramVartanyan** [comment]
> Wait, I just noticed this doesn't seem to work with an ESP32 running at 240MHz (I was doing my tests at 160MHz). The signal looks good, but for some reason the TM1637 doesn't ACK anything at all, and the display stays blank.
> 

Did you removed the ceramic capacitors on the CLK and DATA on the TM1637 PCB?
They are causing troubles by smoothing the edges of the signals and preventing communication on faster speeds.

**Comment by malinges** [comment]
No I didn't, but I think I understand what's causing the issue, and it's not the capacitors (which apparently are there to reduce sensitivity to external EMI).

My display started working again as soon as I added delays between pulling CLK low and updating DIO for the next clock cycle. My theory is that before adding these delays, these level changes were so close to each other (especially with the ESP32 running at 240MHz) that the TM1637 ended up seeing DIO change before it saw CLK going low. And according to the datasheet, changing DIO while CLK is high is a protocol violation, which is why the TM1637 discarded all bytes and ended up doing nothing.

The first clue was when the display started working again when I increased the GPIO drive strength from the default 2 to the max 3. This indicated a timing issue. And sure enough, adding a couple delays where both lines used to be changed at the same time fixed the problem.

The capacitors aren't the culprit here: with these additional delays (and the capacitors) I was able to drive the display at about 240kHz without issues.

**Comment by malinges** [comment]
Here you go, ACKs at about 240kHz with the capacitors :wink: 

scrn-2020-09-13-18-45-16

I won't push that though, 240kHz is uncomfortably close to the theoretical max of 250kHz specified in the datasheet, and might not work in all situations. But hey, with my setup, it works!

**Comment by malinges** [comment]
As far as I know, the code is now ready to merge. Could you test it and tell me if it works with your hardware?

**Comment by petrows** [comment]
Thank you a lot for your PR. Unfortunately i don't have proper HW right now, so i will merge this PR

**Pull request merged**
